# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT

description: Composing multiple LED strip devices into one virtual device

compatible: "zmk,led-strip-composite"

properties:
  chain-length:
    type: int
    required: true

child-binding:
  description: "Details of an included led_strip devices"
  properties:
    led-strip:
      type: phandle
      required: true
